export type SettingsDefinition = { key: string; value: unknown; description: string };

const S = (key: string, value: unknown, description: string): SettingsDefinition => ({ key, value, description });

export const settingsDefinitions: readonly SettingsDefinition[] = [
  S('auth.otp_ttl_min', 10, 'FR-CU-04: minutes an OTP code stays valid.'),
  S('auth.otp_max_attempts', 5, 'FR-CU-04: verification attempts before a code is locked.'),
  S('auth.otp_resend_cooldown_sec', 60, 'Seconds before another OTP may be requested for the same target.'),
  S('auth.login_max_attempts', 5, 'FR-CU-01: wrong passwords tolerated before the identifier is rate-limited.'),
  S('auth.login_window_min', 15, 'NFR-SE-06: window the login attempt counter applies over.'),
  S('auth.staff_totp_required', true, 'NFR-SE-07: staff roles must pass TOTP before reaching staff routes.'),
  S('booking.offer_timeout_min', 15, 'BR-01: minutes an offer stays open before the next provider is offered.'),
  S('booking.free_cancel_hours', 4, 'Hours before the slot within which a customer cancels free.'),
  S('booking.late_cancel_fee_paisa', 50_000, 'Late cancellation fee charged in paisa.'),
  S('booking.no_show_grace_min', 30, 'Minutes after the slot start before a no-show can be reported.'),
  S('booking.pending_payment_timeout_min', 15, 'BR-05: minutes an online checkout holds a slot before ABANDONED.'),
  S('booking.max_offers', 5, 'Maximum providers offered per booking before UNFULFILLED.'),
  S('booking.max_offer_window_min', 60, 'Total auto-assign offer window in minutes.'),
  S('booking.travel_buffer_min', 30, 'BR-08: travel buffer added either side of a slot.'),
  S('booking.max_free_reschedules', 1, 'Reschedules allowed without a fee.'),
  S('booking.evidence_required', true, 'Before and after photos are mandatory to complete a job.'),
  S('booking.emergency_surcharge_pct', 25, 'Surcharge applied to emergency bookings.'),
  S('commission.default_pct', 15, 'Global commission percentage snapshotted onto a booking at checkout.'),
  S('verification.sla_min', 30, 'BR-11: minutes to verify an online booking.'),
  S('verification.cash_sla_min', 15, 'BR-12: minutes to verify a cash booking.'),
  S('verification.calling_hours', { start: '08:00', end: '22:00', timeZone: 'Asia/Karachi' }, 'Calling window for verification calls.'),
  S('verification.time_bands', ['08:00-12:00', '12:00-17:00', '17:00-22:00'], 'Distinct call attempt bands.'),
  S('verification.max_attempts', 3, 'Attempts before the link fallback is sent.'),
  S('verification.auto_release_hours', 72, 'Hours after completion before auto-release.'),
  S('verification.post_release_complaint_days', 7, 'Days after release a customer may still complain.'),
  S('verification.b_escalation_hours', 24, 'Hours before a silent Tier B call escalates to Tier A.'),
  S('verification.lock_timeout_min', 10, 'BR-26: minutes before a stale agent lock is swept back to the queue.'),
  S('verification.force_tier_a', false, 'BR-25: force every verification into Tier A.'),
  S('verification.require_verified_cnic', true, 'Approval requires a VERIFIED CNIC document.'),
  S('tier.first_jobs', 5, 'R1: provider verified-job count below which the booking routes to Tier A.'),
  S('tier.value_threshold_paisa', 1_500_000, 'R2: job value above which the booking routes to Tier A.'),
  S('tier.sample_rate', 0.1, 'R3: probability a routine booking is sampled into Tier A.'),
  S('tier.min_time_ratio', 0.4, 'R4: anomaly when work took less than this share of the booked duration.'),
  S('rework.window_hours', 48, 'Hours the provider has to return for rework.'),
  S('flags.window_days', 90, 'Rolling window for provider conduct flags.'),
  S('flags.review_count', 3, 'Flag review trigger count.'),
  S('provider.cancel_review', { count: 3, days: 30 }, 'Cancellations in this window trigger a provider review.'),
  S('evidence.geofence_radius_m', 200, 'BR-09: geofence radius for start and complete check-ins.'),
  S('evidence.photo_max_bytes', 5_242_880, 'Maximum accepted evidence upload size in bytes.'),
  S('evidence.photo_max_edge_px', 1_600, 'Client-side compression target for evidence photos.'),
  S('cash.debt_ceiling_paisa', 500_000, 'Wallet debt above which the provider is offer-blocked.'),
  S('rating.recent_weight', 2, 'Weight of the most recent ratings in the reputation score.'),
  S('rating.poor_threshold', 3, 'Average rating at or below which a low-rating flag is raised.'),
  S('demerit.expiry_days', 180, 'Days after which a demerit award expires.'),
  S('demerit.decay_days', 30, 'Interval at which demerit points decay.'),
  S('penalty.reply_hours', 48, 'Hours a provider has to reply to a proposed penalty.'),
  S('penalty.max_fine_paisa', 1_000_000, 'Cap on the fine for a single job.'),
  S('penalty.no_show_fine_paisa', 100_000, 'Suggested fine for a provider no-show.'),
  S('payout.cycle', { frequency: 'WEEKLY', day: 'MONDAY', time: '10:00' }, 'BR-50: payout batch schedule.'),
  S('payout.min_amount_paisa', 100_000, 'Minimum wallet balance that can be requested for payout.'),
  S('recording.retention_days', 180, 'BR-55: call recording retention.'),
  S('complaint.sla_hours', { SAFETY: 1, HIGH: 24, NORMAL: 72 }, 'BR-56: first-response SLA by severity.'),
  S('ranking.weights', { rating: 0.35, distance: 0.25, completion: 0.2, response: 0.1, recency: 0.1 }, 'BR-60: search ranking weights.'),
  S('rating.bayesian_prior', 3.5, 'CL-17: neutral prior rating for providers with few reviews.'),
  S('rating.bayesian_weight', 5, 'CL-17: weight of the Bayesian prior in the weighted score.')
];

export const settingsDefaults = (): Map<string, unknown> => new Map(settingsDefinitions.map(definition => [definition.key, definition.value]));
